inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'

urlpatterns = [
    path("", views.item_list, name="item_list"),
    # path("amount/", views.amount_ajax, name="amount_ajax"),
    path("<int:pk>/", views.item_read, name="item_read"),
    path("create/", views.item_create, name="item_create"),
    path("update/<int:pk>/", views.item_update, name="item_update"),
    path("delete/<int:pk>/", views.item_delete, name="item_delete"),

path("account/", views.account_list, name="account_list"),
    path("account/<int:pk>/", views.account_read, name="account_read"),
    path("account/create/", views.account_create, name="account_create"),
    path("account/update/<int:pk>/", views.account_update, name="account_update"),
    path("account/delete/<int:pk>/", views.account_delete, name="account_delete"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inventory/', include("inventory.urls")),
    path("", lambda req: redirect("inventory:item_list")),
]

inventory/models.py
from django.db import models

class Account(models.Model):
    name = models.CharField(max_length=50)
    call = models.CharField(max_length=11, null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name

class Item(models.Model):
    title = models.CharField(max_length=50, null=True)
    image = models.ImageField(null=True, blank=True, upload_to="image")
    content = models.TextField(null=True, blank=True)
    price = models.PositiveIntegerField(null=True, blank=True)
    amount = models.PositiveIntegerField(null=True)
    account = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title

inventory/forms.py
from django import forms
from .models import Account, Item


class ItemForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = ("title", "image", "content", "price", "amount", "account")


class AccountForm(forms.ModelForm):

    class Meta:
        model = Account
        fields = ("name", "call", "address")

inventory/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from inventory.forms import ItemForm, AccountForm
from inventory.models import Item, Account


def item_list(request):
    items = Item.objects.all()
    ctx = {
        "items": items
    }
    return render(request, "inventory/item_list.html", ctx)


@require_POST
def amount_ajax(request):
    pk = request.POST.get("pk")
    status = request.POST.get("status")
    item = get_object_or_404(Item, pk=pk)

    if status == "plus":
        item.amount += 1
    else:
        if item.amount > 0:
            item.amount -= 1
        else:
            redirect('inventory:item_list')
    item.save()
    ctx = {
        "amount": item.amount,
    }
    return JsonResponse(ctx)


def item_read(request, pk):
    item = Item.objects.get(pk=pk)
    ctx = {
        "item": item
    }
    return render(request, "inventory/item_detail.html", ctx)


def item_create(request):
    if request.method == "POST":
        form = ItemForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save()
            return redirect("inventory:item_read", item.pk)
    else:
        form = ItemForm()
        ctx = {
            "form": form
        }
        return render(request, "inventory/item_create.html", ctx)


def item_update(request, pk):
    item = Item.objects.get(pk=pk)

    if request.method == "POST":
        form = ItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            item = form.save()
        return redirect("inventory:item_read", item.pk)

    else:
        form = ItemForm(instance=item)
        ctx = {
            "form": form
        }
        return render(request, "inventory/item_update.html", ctx)


def item_delete(request, pk):
    item = Item.objects.get(pk=pk)

    if request.method == "POST":
        item.delete()
        return redirect("inventory:item_list")

    return redirect("inventory:item_read", item.pk)

def account_list(request):
    accounts = Account.objects.all()
    ctx = {
        "accounts": accounts
    }
    return render(request, "inventory/account_list.html", ctx)


def account_read(request, pk):
    account = Account.objects.get(pk=pk)
    ctx = {
        "account": account
    }
    return render(request, "inventory/account_read.html", ctx)


def account_create(request):
    if request.method == "POST":
        form = AccountForm(request.POST)
        if form.is_valid():
            account = form.save()
            return redirect("inventory:account_read", account.pk)
    else:
        form = AccountForm()
        ctx = {
            "form": form
        }
        return render(request, "inventory/account_create.html", ctx)


def account_update(request, pk):
    account = Account.objects.get(pk=pk)

    if request.method == "POST":
        form = AccountForm(request.POST, instance=account)
        if form.is_valid():
            account = form.save()
        return redirect("inventory:account_read", account.pk)

    else:
        form = AccountForm(instance=account)
        ctx = {
            "form": form
        }
        return render(request, "inventory/account_update.html", ctx)


def account_delete(request, pk):
    account = Account.objects.get(pk=pk)

    if request.method == "POST":
        account.delete()
        return redirect("inventory:account_list")

    return redirect("inventory:account_read", account.pk)

inventory/templates/inventory/account_create.html
{% extends "inventory/layout.html" %}

{% block content %}
    <div id="head">
        <div>Account Register</div>
        <div>거래처 등록 페이지 입니다. 여기 부연설명은 아무 이유 없고 그냥 예쁘라고 넣었어요.</div>
    </div>

    <div id="item-form">
        <form action="" method="post" class="account_form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">저장</button>
        </form>
    </div>
{% endblock %}

inventory/templates/inventory/account_list.html
{% extends "inventory/layout.html" %}

{% block content %}
    <div id="head">
        <div>Account List</div>
        <div>거래처 목록 페이지 입니다. 여기 부연설명은 아무 이유 없고 그냥 예쁘라고 넣었어요.</div>
    </div>

    <div id="accounts">
        {% for account in accounts %}
            <div class="account">
                <div class="name"><a href="{% url 'inventory:account_read' account.pk %}">{{ account.name }}</a></div>
                <div class="call">{{ account.call }}</div>
                <div class="address">{{ account.address }}</div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

inventory/templates/inventory/account_read.html
{% extends "inventory/layout.html" %}

{% block content %}
    <div id="head">
        <div>Account Detail</div>
        <div>거래처 세부내용 페이지 입니다. 여기 부연설명은 아무 이유 없고 그냥 예쁘라고 넣었어요.</div>
    </div>

    <div id="wrap">
        <div id="background">
            <div id="account">
                <div class="name">{{ account.name }}</div>
                <div class="call">{{ account.call }}</div>
                <div class="address">{{ account.address }}</div>
            </div>
            <div id="item">
                <div class="list-name">거래 상품 목록</div>
                <div class="list">
                    {% for item in account.item_set.all %}
                        <div><a href="{% url 'inventory:item_read' item.pk %}">{{ item.title }}</a></div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <div id="account-buttons">
        <div class="left">
            <form action="{% url 'inventory:account_delete' account.pk %}" method="post">
                {% csrf_token %}
                <div class="delete"><input type="submit" value="삭제"></div>
            </form>
        </div>
        <div class="right">
            <form action="{% url 'inventory:account_list' %}">
                {% csrf_token %}
                <div class="list"><input type="submit" value="목록"></div>
            </form>
            <form action="{% url 'inventory:account_update' account.pk %}">
                {% csrf_token %}
                <div class="update"><input type="submit" value="수정"></div>
            </form>
        </div>
    </div>
{% endblock %}

inventory/templates/inventory/account_update.html
{% extends "inventory/layout.html" %}

{% block content %}
    <div id="head">
        <div>Account Detail Update</div>
        <div>거래처 세부내용 수정 페이지 입니다. 여기 부연설명은 아무 이유 없고 그냥 예쁘라고 넣었어요.</div>
    </div>

    <div id="item-form">
        <form action="" method="post" class="item_form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">저장</button>
        </form>
    </div>
{% endblock %}

inventory/templates/inventory/item_create.html
{% extends "inventory/layout.html" %}

{% block content %}
    <div id="head">
        <div>Item Register</div>
        <div>상품 등록 페이지 입니다. 여기 부연설명은 아무 이유 없고 그냥 예쁘라고 넣었어요.</div>
    </div>

    <div id="item-form">
        <form action="" method="post" class="item_form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">저장</button>
        </form>
    </div>
{% endblock %}

inventory/templates/inventory/item_detail.html
{% extends "inventory/layout.html" %}

{% block content %}
    <div id="head">
        <div>Item Detail</div>
        <div>상품 세부내용 페이지 입니다. 여기 부연설명은 아무 이유 없고 그냥 예쁘라고 넣었어요.</div>
    </div>

    <div id="item-wrap">
        <div id="item">
            {% if item.image %}
                <div class="image"><img src="{{ item.image.url }}" alt=""></div>
            {% endif %}
            <div class="text">
                <div class="title">{{ item.title }}</div>
                <div class="price">가격 : <span>{{ item.price }}</span></div>
                <div class="amount">남은 수량 : <span>{{ item.amount }}</span></div>
                <div class="content">제품 설명 : <span>{{ item.content|linebreaks }}</span></div>
                <div class="account">거래처 : <a href="{% url 'inventory:account_read' item.account.pk %}">{{ item.account }}</a></div>
            </div>
        </div>

        <div id="buttons">
            <div class="left">
                <form action="{% url 'inventory:item_delete' item.pk %}" method="post">
                    {% csrf_token %}
                    <div class="delete"><input type="submit" value="삭제"></div>
                </form>
            </div>
            <div class="right">
                <form action="{% url 'inventory:item_list' %}">
                    {% csrf_token %}
                    <div class="list"><input type="submit" value="목록"></div>
                </form>
                <form action="{% url 'inventory:item_update' item.pk %}">
                    {% csrf_token %}
                    <div class="update"><input type="submit" value="수정"></div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

inventory/templates/inventory/item_list.html
{% extends "inventory/layout.html" %}

{% block content %}
    <div id="head">
        <div>Item List</div>
        <div>상품 목록 페이지 입니다. 여기 부연설명은 아무 이유 없고 그냥 예쁘라고 넣었어요.</div>
    </div>

    <div id="items">
        {% for item in items %}
            <div class="item">
                {% if item.image %}
                    <div class="image"><img src="{{ item.image.url }}" alt=""></div>
                {% endif %}
                <div class="title"><a href="{% url 'inventory:item_read' item.pk %}">{{ item.title }}</a></div>
                <div class="price">가격 : {{ item.price }}</div>
                <div id="amount-{{ item.pk }}" class="amount">남은 수량 : {{ item.amount }}</div>

                <input type="submit" onclick="clickButton({{ item.pk }},'plus')" value="+" class="button">
                <input type="submit" onclick="clickButton({{ item.pk }},'minus')" value="-" class="button">
            </div>
        {% endfor %}
    </div>
{% endblock %}

inventory/templates/inventory/item_update.html
{% extends "inventory/layout.html" %}

{% block content %}
    <div id="head">
        <div>Item Detail Update</div>
        <div>상품 세부내용 수정 페이지 입니다. 여기 부연설명은 아무 이유 없고 그냥 예쁘라고 넣었어요.</div>
    </div>

    <div id="item-form">
        <form action="" method="post" class="item_form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">저장</button>
        </form>
    </div>
{% endblock %}

inventory/templates/inventory/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Inventory Management</title>
<!--    <link rel="stylesheet" href="{% static 'css/layout.css' %}?9">-->
<!--    <link rel="stylesheet" href="{% static 'css/item_list.css' %}?7">-->
<!--    <link rel="stylesheet" href="{% static 'css/item_read.css' %}?10">-->
<!--    <link rel="stylesheet" href="{% static 'css/account_list.css' %}?7">-->
<!--    <link rel="stylesheet" href="{% static 'css/account_read.css' %}?7">-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:200,300,600|Noto+Sans+KR:300,400,700,900=swap" rel="stylesheet">
    {% block headAppend %}
    {% endblock %}
</head>
<body>
    <div id="header">
        <div id="title">
            <a href="{% url 'inventory:item_list' %}">
                Inventory Manage
            </a>
        </div>
        <div id="nav">
            <ul>
                <li><a href="{% url 'inventory:item_create' %}">상품 등록</a></li>
                <li><a href="{% url 'inventory:account_create' %}">거래처 등록</a></li>
                <li><a href="{% url 'inventory:account_list' %}">거래처 관리</a></li>

            </ul>
        </div>
    </div>

    <div id="body">
        {% block content %}
        {% endblock %}
    </div>

    <div id="footer">
        <div>피로그래밍 | 13기 손민주</div>

    </div>
</body>
</html>